# environment.yml (local dev)
name: neuromorpho-ml
channels: [conda-forge]
dependencies:
  - python=3.11
  - ipykernel
  - jupyterlab
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - requests
  # outils de build de site (local/CI)
  - mkdocs
  - pip
  - pip:
      - mkdocs-material
      - jupyter-book
      - myst-nb
      - ghp-import
