title: BioInformatic Notebooks
only_build_toc_files: true

repository:
  url: https://github.com/maximedieudonne/BioInformatic_Notebooks
  path_to_book: book
  branch: master  

sphinx:
  config:
    html_theme_options:
      use_repository_button: true
      use_edit_page_button: true
      use_issues_button: true
      repository_url: https://github.com/maximedieudonne/BioInformatic_Notebooks
      path_to_docs: "book"
    html_context:
      github_user: maximedieudonne
      github_repo: BioInformatic_Notebooks
      github_version: master  
      doc_path: book
