name: build-and-deploy-site
on:
  push:
    branches: [master]  
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install site builders
        run: |
          pip install mkdocs-material jupyter-book ghp-import

      - name: Configure git for push
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"

      - name: Deploy to gh-pages
        run: ghp-import -n -p -f site
